### PR TITLE
Update for the flag

### PR DESCRIPTION
**Pull request by Skender-H**
Hello, I've finally figured out how to fix the flagg issue on my student block, which honestly wasn't as hard as I made myself believe it to be.

### CODE REVIEW

**Review by GaryClarke — CHANGES_REQUESTED** [review]
Can you make sure you have pulled the latest changes into your code and send again.

**Comment by Skender-H** [comment]
> Can you make sure you have pulled the latest changes into your code and send again.

It says "Already up to date" when I run the pull command. On my fork it also only mentions that I'm 3 commits ahead. If theres some sort of issue, then I don't know how to fix it. 

Unless if removing a branch I used previously to pull and merge into the main branch would help?

**Comment by Skender-H** [comment]
I've deleted the branch and moved the flag a bit but other than that the code is up to date with the main. I've tried pulling but no matter what it insists that I already am up to date.

**Review by garyclarketech — APPROVED** [review]

**Comment by garyclarketech** [comment]
It's ok..was my mistake 🤭 Looks good...thanks again!

**Pull request merged**
