### PR TITLE
Adding a new student

### PR DESCRIPTION
**Pull request by Skender-H**
Hi! It took me a while to figure out why I wasn't able to create a pull request, but I'm glad I finally figured it out! ^°^)

### CODE REVIEW

**Review by GaryClarke — CHANGES_REQUESTED** [review]
Thanks for the PR!
Can you send again but only commit the students.html file? 
There is a composer.json and some .idea files which are superfluous.

**Comment by Skender-H** [comment]
> 

of course!

**Comment by Skender-H** [comment]
> Thanks for the PR! Can you send again but only commit the students.html file? There is a composer.json and some .idea files which are superfluous.

Hi! I believe I've fixed the issue, though a bit uncertain if I have done things correctly.

**Review by GaryClarke — APPROVED** [review]

**Comment by garyclarketech** [comment]
Looks good! Merged 🤝

**Pull request merged**
